CREATE DATABASE pai_db;
use pai_db;

CREATE USER pai_user identified by "qwe123";
# CREATE, SELECT, INSERT, DELETE, UPDATE, DROP, REFERENCES
GRANT CREATE, ALTER, SELECT, INSERT, DELETE, UPDATE, DROP, REFERENCES ON pai_db.* TO pai_user;